### 판다스 기초

판다스 패키지 로드

import pandas as pd

In [78]:
import pandas as pd
import numpy as np

### 핵심 자료구조

-series와 DATAFRAME

### Series

- 1차원 데이터를 표현하는 자료구조. 인덱스가 붙어있는 한줄짜리 데이터. 1차원 배열과 흡사

In [79]:
np_scores =np.array([85,90,95,80])
np_scores

array([85, 90, 95, 80])

In [80]:
scores = pd.Series([85,90,95,80])

scores

0    85
1    90
2    95
3    80
dtype: int64

- 시리즈 작성 시 인덱스를 커스터마이징 할 수 있음

In [81]:

scores = pd.Series(
    [85, 90, 95, 80],
    index=['홍길동', '김철수', '이영희', '박민수']
)

scores

홍길동    85
김철수    90
이영희    95
박민수    80
dtype: int64

In [82]:
# 기존 인덱스는 사용 불가 
# scores[0]

In [83]:
# 인데스가 숫자에서 문자열로 연결

scores ['홍길동']

np.int64(85)

#### series 연산

In [84]:
#화면에 출력되고 끝 (원래 값이 변경되는게 아니다)

scores+5

홍길동     90
김철수     95
이영희    100
박민수     85
dtype: int64

In [85]:
scores /2

홍길동    42.5
김철수    45.0
이영희    47.5
박민수    40.0
dtype: float64

In [86]:
scores # 원래 주어진 값은 변경되지 않는다.

홍길동    85
김철수    90
이영희    95
박민수    80
dtype: int64

In [87]:
scores.mean()

np.float64(87.5)

In [88]:
scores.max()

np.int64(95)

In [89]:
scores.min()

np.int64(80)

In [90]:
scores.sum()

np.int64(350)

In [91]:
scores.std()

np.float64(6.454972243679028)

In [92]:
scores.count()

np.int64(4)

- NumPy와 통계함수가 거의 유사하게 존재 
- 속도문제로 예전에는 NumPy를 많이 사용했지만 현재는 사용률이 높지 않음

#### DataFrame

- Pandas 2차원 표형태 데이터 표현하는 자료구조
- Pandas의 기본 자료구조형
- 엑셀, CSV (엑셀 형태의 텍스트 파일), DB테이블과 동일한 구조

In [93]:
#dataframe을 직접 생성할때 사용
# 파이썬 딕셔너리 사용

raw_data = {
    'name': ['홍길동', '김철수', '이영희', '박민수','성유고','에슐리'],
    'age': [20, 21, 22, 23,30, 29],
    'major': ['데이터분석', '웹개발', '인공지능', '임베디드','인공지능', '웹개발'],
    'score': [85, 90, 95, 80,90,100]
}

raw_data

{'name': ['홍길동', '김철수', '이영희', '박민수', '성유고', '에슐리'],
 'age': [20, 21, 22, 23, 30, 29],
 'major': ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
 'score': [85, 90, 95, 80, 90, 100]}

In [94]:
# 일반적으로 dataframe 줄여서 df로 변수명 많이 활용

df = pd.DataFrame(raw_data)
df

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80
4  성유고   30   인공지능     90
5  에슐리   29    웹개발    100

#### DataFrame 구조 확인

- NumPy의 shape ,size, dtype, ndim 과 유사한 기능

In [95]:
df.head() # 앞쪽부터 무조건 5개 데이터만 나옴 기본이 5

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80
4  성유고   30   인공지능     90

In [96]:
# 기본 5를 3으로 변경
df.head(3)

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95

In [97]:
# 마지막 데이터 확인 . 기본5
df.tail()

  name  age major  score
1  김철수   21   웹개발     90
2  이영희   22  인공지능     95
3  박민수   23  임베디드     80
4  성유고   30  인공지능     90
5  에슐리   29   웹개발    100

In [98]:
df.tail(2) #끝에서 두개만 확인

  name  age major  score
4  성유고   30  인공지능     90
5  에슐리   29   웹개발    100

In [99]:
# 행과 열의 개수 shape는 함수가 아니라 속성

df.shape

(6, 4)

In [100]:
df.columns

Index(['name', 'age', 'major', 'score'], dtype='str')

In [101]:
df.index # stop은 열+1

RangeIndex(start=0, stop=6, step=1)

In [102]:
# 컬럼별 타입과 결측값 확인

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   age     6 non-null      int64
 2   major   6 non-null      str
 3   score   6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

#### 기본통계

- 수치타입만 나옴

In [103]:
df.describe()

             age       score
count   6.000000    6.000000
mean   24.166667   90.000000
std     4.262237    7.071068
min    20.000000   80.000000
25%    21.250000   86.250000
50%    22.500000   90.000000
75%    27.500000   93.750000
max    30.000000  100.000000

In [104]:
df.age.mean()

np.float64(24.166666666666668)

In [105]:
df['age'].mean()

np.float64(24.166666666666668)

In [106]:
df.age.median()

np.float64(22.5)

In [107]:
# 25% 값 /1분위 수
df.age.quantile(0.25)

np.float64(21.25)

In [108]:
# 50% 값 /2 분위수 = median 
df.age.quantile(0.5)

np.float64(22.5)