### 판다스 기초

판다스 패키지 로드

In [106]:
import pandas as pd

In [107]:
#dataframe을 직접 생성할때 사용
# 파이썬 딕셔너리 사용

raw_data = {
    'name': ['홍길동', '김철수', '이영희', '박민수','성유고','에슐리'],
    'age': [20, 21, 22, 23,30, 29],
    'major': ['데이터분석', '웹개발', '인공지능', '임베디드','인공지능', '웹개발'],
    'score': [85, 90, 95, 80,90,100]
}

raw_data

{'name': ['홍길동', '김철수', '이영희', '박민수', '성유고', '에슐리'],
 'age': [20, 21, 22, 23, 30, 29],
 'major': ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
 'score': [85, 90, 95, 80, 90, 100]}

#### 기본통계

In [108]:
# 숫자타입 필드만 통계가능
df.describe()

             age       score  scrore_bonus
count   8.000000    8.000000      6.000000
mean   24.250000   89.875000     95.000000
std     3.615443    6.034129      7.071068
min    20.000000   80.000000     85.000000
25%    21.750000   87.250000     91.250000
50%    23.500000   90.000000     95.000000
75%    26.000000   92.000000     98.750000
max    30.000000  100.000000    105.000000

#### 컬럼 선택 (열)

In [109]:
import pandas as pd      # 1. pandas 불러오기
raw_data = {...}         # 2. 원본 데이터 만들기
df = pd.DataFrame(raw_data)  # 3. DataFrame 만들기

In [110]:
# DataFrame에서 필요한 컬럼만 호가인 또는 할당(복사)
import pandas as pd

raw_data = {
    'name': ['홍길동', '김철수', '이영희', '박민수', '최유진', '정다은'],
    'age': [20, 21, 22, 23, 30, 29],
    'major': ['데이터분석', '웹개발', '컴퓨터공학', '프론트엔드', '컴퓨터공학', '웹개발'],
    'score': [85, 90, 95, 80, 90, 100]
}

df = pd.DataFrame(raw_data)

In [111]:
#대 괄호가 두개인지 하나인지로 시리즈와 데이터 프레임 구분 

df[['name','age']]

  name  age
0  홍길동   20
1  김철수   21
2  이영희   22
3  박민수   23
4  최유진   30
5  정다은   29

### 로우 선택 (행)

In [112]:
# 인덱스 이름을 기준 location
df.loc[0]

name       홍길동
age         20
major    데이터분석
score       85
Name: 0, dtype: object

In [113]:
# 위치번호 기준 인덱스를 다른 값으로 바꿨을때 사용하는 방법
df.iloc[0]

name       홍길동
age         20
major    데이터분석
score       85
Name: 0, dtype: object

In [114]:
#시리즈의 인덱스로 각 열의 값을 확인 
df.loc[0]['major']

'데이터분석'

In [115]:
#슬라이싱으로 여러행을 선택
#원래 파이썬 슬라이싱 규칙에서 벗어남 뒤에수가 N-1이 아님
df.loc[0:2]

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22  컴퓨터공학     95

In [116]:
data=[1,2,3,5,6,]

In [117]:
data[0:2]

[1, 2]

In [118]:
df.iloc[0:2]

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90

##### 행선택, 인덱스행 (loc)과 위치값행 (iloc차이)

In [119]:
df2 = pd.DataFrame(
    raw_data,
    index=['s0001', 's0002', 's0003', 's0005', 's0009', 's0010']
)
df2

      name  age  major  score
s0001  홍길동   20  데이터분석     85
s0002  김철수   21    웹개발     90
s0003  이영희   22  컴퓨터공학     95
s0005  박민수   23  프론트엔드     80
s0009  최유진   30  컴퓨터공학     90
s0010  정다은   29    웹개발    100

In [120]:
df2.loc['s0002': 's0005']

      name  age  major  score
s0002  김철수   21    웹개발     90
s0003  이영희   22  컴퓨터공학     95
s0005  박민수   23  프론트엔드     80

In [121]:
#파이썬 배열 인덱스와 동일
df2.iloc[1:4]

      name  age  major  score
s0002  김철수   21    웹개발     90
s0003  이영희   22  컴퓨터공학     95
s0005  박민수   23  프론트엔드     80

loc는 부여받은 인덱스로 행선택, 슬라이싱
iloc는 원래부터 위치값(파이썬 배열의 인덱스)와 동일

#### 행과 열을 함께 선택

In [122]:
df.loc[0,'name']

'홍길동'

In [123]:
#인덱스를 따로 부여하지 앟은 DF에서 행과 열 선택
df.loc[0:2,['name','age']]

  name  age
0  홍길동   20
1  김철수   21
2  이영희   22

In [124]:
#인덱스를 따로 지정해준 DF에서 행과 열 선택
df2.loc['s0001':'s0003',['name','age']]

      name  age
s0001  홍길동   20
s0002  김철수   21
s0003  이영희   22

In [125]:
df3 = df2.loc['s0001':'s0003',['name','age']]
df3

      name  age
s0001  홍길동   20
s0002  김철수   21
s0003  이영희   22

### 조건 조회

- SQL WHERE 절과 동일

In [126]:
df['score'] >=90

0    False
1     True
2     True
3    False
4     True
5     True
Name: score, dtype: bool

In [127]:
df[df['score']>=90]

  name  age  major  score
1  김철수   21    웹개발     90
2  이영희   22  컴퓨터공학     95
4  최유진   30  컴퓨터공학     90
5  정다은   29    웹개발    100

- numpy와 동일한 조건 연산
- 파이썬:and, or, not 사용
- numpy, pandas: & ,| , ~ 사용
- 연산자 우선 순위로 각 조건은 반드시 () 를 사용할 것

In [128]:
#점수가 90점 초과이고 나이가 21살 이상인 학생 데이터

df[(df['score'] > 90) & (df['age'] >= 21)]

  name  age  major  score
2  이영희   22  컴퓨터공학     95
5  정다은   29    웹개발    100

In [129]:
#점수가 90점 초과이거나 나이가 21살 이상이거나 둘중에 하나로 참인 데이터 조회

df[(df['score'] > 90) | (df['age'] >= 21)]

  name  age  major  score
1  김철수   21    웹개발     90
2  이영희   22  컴퓨터공학     95
3  박민수   23  프론트엔드     80
4  최유진   30  컴퓨터공학     90
5  정다은   29    웹개발    100

#### 컬럼 추가
- 사용하던 DF이외에 필요한 컬럼이 생길때 추가

In [130]:
df

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22  컴퓨터공학     95
3  박민수   23  프론트엔드     80
4  최유진   30  컴퓨터공학     90
5  정다은   29    웹개발    100

In [131]:
#80점을 초과하는 학생만 통과
#같은 이름 칼럼은 새로 추가 안됨
df['pass'] = df['score']>80
df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   22  컴퓨터공학     95   True
3  박민수   23  프론트엔드     80  False
4  최유진   30  컴퓨터공학     90   True
5  정다은   29    웹개발    100   True

In [132]:
df['score_bonus'] = df['score'] + 5
df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           90
1  김철수   21    웹개발     90   True           95
2  이영희   22  컴퓨터공학     95   True          100
3  박민수   23  프론트엔드     80  False           85
4  최유진   30  컴퓨터공학     90   True           95
5  정다은   29    웹개발    100   True          105

#### 컬럼 수정
- 기존 컬럼 수정

In [133]:
df['score_bonus'] = df['score_bonus'] - 2
df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           88
1  김철수   21    웹개발     90   True           93
2  이영희   22  컴퓨터공학     95   True           98
3  박민수   23  프론트엔드     80  False           83
4  최유진   30  컴퓨터공학     90   True           93
5  정다은   29    웹개발    100   True          103

In [134]:
# 행 선택에서 score_bonus 점수가 100점이 넘는 행만 선택 후 score_bonus열을 100점으로 수정한다
df.loc [df['score_bonus']>100,'score_bonus'] =100
df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           88
1  김철수   21    웹개발     90   True           93
2  이영희   22  컴퓨터공학     95   True           98
3  박민수   23  프론트엔드     80  False           83
4  최유진   30  컴퓨터공학     90   True           93
5  정다은   29    웹개발    100   True          100

#### 컬럼 삭제
- 불필요한 컬럼은 삭제

In [135]:
df.drop(columns=['score_bonus'], inplace=True)

In [136]:
df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   22  컴퓨터공학     95   True
3  박민수   23  프론트엔드     80  False
4  최유진   30  컴퓨터공학     90   True
5  정다은   29    웹개발    100   True

In [148]:
df.drop(columns=['score_bonus'], inplace=True, errors='ignore')

In [149]:
df

  name   age  major  score   pass
0  홍길동  20.0  데이터분석   85.0   True
1  김철수  21.0    웹개발   90.0   True
2  이영희  22.0  컴퓨터공학   95.0   True
3  박민수  23.0  프론트엔드   80.0  False
4  최유진  30.0  컴퓨터공학   90.0   True
5  정다은  29.0    웹개발  100.0   True
6  최지우  24.0    웹개발   88.0   True
7  박선호  25.0   인공지능   91.0   None

#### 행 추가

- 새로운 행추가 방법

In [150]:
df.loc[6] = ['최지우', 24, '웹개발', 88, True]
df

  name   age  major  score   pass
0  홍길동  20.0  데이터분석   85.0   True
1  김철수  21.0    웹개발   90.0   True
2  이영희  22.0  컴퓨터공학   95.0   True
3  박민수  23.0  프론트엔드   80.0  False
4  최유진  30.0  컴퓨터공학   90.0   True
5  정다은  29.0    웹개발  100.0   True
6  최지우  24.0    웹개발   88.0   True
7  박선호  25.0   인공지능   91.0   None

In [152]:
df.loc[7] = ['박선호', 25, '인공지능', 91, None]
df

  name   age  major  score   pass
0  홍길동  20.0  데이터분석   85.0   True
1  김철수  21.0    웹개발   90.0   True
2  이영희  22.0  컴퓨터공학   95.0   True
3  박민수  23.0  프론트엔드   80.0  False
4  최유진  30.0  컴퓨터공학   90.0   True
5  정다은  29.0    웹개발  100.0   True
6  최지우  24.0    웹개발   88.0   True
7  박선호  25.0   인공지능   91.0   None

In [153]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   age     8 non-null      float64
 2   major   8 non-null      str
 3   score   8 non-null      float64
 4   pass    7 non-null      object
dtypes: float64(2), object(1), str(2)
memory usage: 452.0+ bytes

#### 데이터 읽기 쓰기

- 일반적으로 CSV 가장 많이 사용
- DB도 연동가능

In [154]:
df_bookstore = pd.read_csv('../data/부산지역서점.csv')
df_bookstore

,연번,시설명,전화번호,시군구,위도,경도,정렬번호
0,0,동사서독,0507-1396-1606,부산 금정구 금정로 87 2층,35.232421,129.086648,67
1,1,흰돌서점,051-625-9633,부산 수영구 남천서로32번길 38 흰돌서점,35.145707,129.106685,1
2,2,효원도서,051-517-6871,부산 금정구 부산대학로 63 (장전동),35.231481,129.084427,2
3,3,화명서점,051-337-0140,부산 북구 화명신도시로 130 로얄팰리스 110호 화명서점,35.235544,129.011331,3
4,4,현대서점,051-581-7963,부산 금정구 남산로 30 현대서점 (남산동),35.267302,129.088872,4
...,...,...,...,...,...,...,...
62,62,책과아이들,051-506-1448,부산 연제구 교대로16번길 20,35.196453,129.078185,62
63,63,책마을,051-753-8685,부산 연제구 안연로8번길 19 3층,35.188471,129.102055,63
64,64,카프카의 밤,051-665-5516,부산 연제구 고분로191번길 20,35.186167,129.104129,64
65,65,동네책방 아인,051-665-5516,부산 연제구 월드컵대로 221 다우빌딩 2층,35.188866,129.072650,65
66,66,책방 감,051-581-3318,부산 연제구 교대로24번길 10,35.195938,129.077150,66

In [155]:
#데이터 쓰기
df.to_csv('../data/학생정보.csv',encoding='utf-8')

#### Excel

In [156]:
df_bookstore2= pd.read_excel('../data/부산지역서점.xlsx')
df_bookstore2

,연번,시설명,전화번호,시군구,위도,경도,정렬번호
0,0,동사서독,0507-1396-1606,부산 금정구 금정로 87 2층,35.232421,129.086648,67
1,1,흰돌서점,051-625-9633,부산 수영구 남천서로32번길 38 흰돌서점,35.145707,129.106685,1
2,2,효원도서,051-517-6871,부산 금정구 부산대학로 63 (장전동),35.231481,129.084427,2
3,3,화명서점,051-337-0140,부산 북구 화명신도시로 130 로얄팰리스 110호 화명서점,35.235544,129.011331,3
4,4,현대서점,051-581-7963,부산 금정구 남산로 30 현대서점 (남산동),35.267302,129.088872,4
...,...,...,...,...,...,...,...
62,62,책과아이들,051-506-1448,부산 연제구 교대로16번길 20,35.196453,129.078185,62
63,63,책마을,051-753-8685,부산 연제구 안연로8번길 19 3층,35.188471,129.102055,63
64,64,카프카의 밤,051-665-5516,부산 연제구 고분로191번길 20,35.186167,129.104129,64
65,65,동네책방 아인,051-665-5516,부산 연제구 월드컵대로 221 다우빌딩 2층,35.188866,129.072650,65
66,66,책방 감,051-581-3318,부산 연제구 교대로24번길 10,35.195938,129.077150,66

In [ ]:
#### PostgresSQL

- psypg

In [157]:
import psycopg

In [162]:
conn= psycopg.connect(

host='localhost',
port= 5432,
dbname='ai_db',
user='postgres',
password='123456'

)

In [163]:
sql = 'select *from students'
df_postgres_students = pd.read_sql(sql,conn)
df_postgres_students

C:\Users\User\AppData\Local\Temp\ipykernel_23144\3558773882.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_postgres_students = pd.read_sql(sql,conn)

    id name             email  age  major                 created_at
0    1  김철수   kim@example.com   21   인공지능 2026-09-17 15:51:30.739409
1    2  이영희   lee@example.com   22  데이터분석 2026-09-17 15:51:30.739409
2    3  박민수  park@example.com   23    웹개발 2026-09-17 15:51:30.739409
3    4  최지훈  choi@example.com   24   임베디드 2026-09-17 15:51:30.739409
4    5  정수빈  jung@example.com   20   클라우드 2026-09-17 15:51:30.739409
5    7  이찬혁   lee@example.com   26   임베디드 2026-09-18 10:36:34.842730
6    8  주예찬   joo@example.com   24   인공지능 2026-09-18 12:09:31.810582
7    9  이찬혁   lee@example.com   26   임베디드 2026-09-18 12:09:31.810582
8   11  애슐리  ashuly@gmail.com   30   영어영문 2026-09-22 12:09:31.911910
9   12  애슐리  ashuly@gmail.com   30   영어영문 2026-09-22 12:09:33.308576
10  13  애슐리  ashuly@gmail.com   30   영어영문 2026-09-22 12:09:43.476186
11  14  희동이    dupa@gmail.com   40   체육학과 2026-09-22 13:51:23.262650

- PostgresSQL로 데이터 저장은 추후

### 실습

- 상품 데이터 활용

In [187]:
data= {
    'product':['키보드','마우스','모니터','USB','노트북'],
    'category': ['주변기기','주변기기','디스플레이','저장장치','컴퓨터'],
     'price':[30000,15000,250000,12000,1200000],
     'stock':[10,30,5,50,3]
}

df_products=pd.DataFrame(data)

1. 전체 데이터 출력
2.product, priuce 컬럼 출력
3.가격이 50000원 이상인 상품만 출력
4.재고가 10개 이상인 상품만 출력
5.totla_value 컬럼 추가, 계산식은 price*stock
6.전체 재고의 합계 출력
7.카테고리가 주변기기인 상품만 출력

In [188]:
# 1번
df_products

  product category    price  stock
0     키보드     주변기기    30000     10
1     마우스     주변기기    15000     30
2     모니터    디스플레이   250000      5
3     USB     저장장치    12000     50
4     노트북      컴퓨터  1200000      3

In [189]:
# 2번
df_products[['product','price']]

  product    price
0     키보드    30000
1     마우스    15000
2     모니터   250000
3     USB    12000
4     노트북  1200000

In [190]:
#3번
df_products['price']>50000

0    False
1    False
2     True
3    False
4     True
Name: price, dtype: bool

In [191]:
#위에 결과값을 한번 더 감싸준다 df로
df_products[df_products['price']>50000]

  product category    price  stock
2     모니터    디스플레이   250000      5
4     노트북      컴퓨터  1200000      3

In [192]:
df_products['stock']>=10

0     True
1     True
2    False
3     True
4    False
Name: stock, dtype: bool

In [193]:
#4반
df_products[df_products['stock']>=10]

  product category  price  stock
0     키보드     주변기기  30000     10
1     마우스     주변기기  15000     30
3     USB     저장장치  12000     50

In [194]:
# 5번
df_products['total_value'] =df_products['price'] * df_products['stock']
df_products

  product category    price  stock  total_value
0     키보드     주변기기    30000     10       300000
1     마우스     주변기기    15000     30       450000
2     모니터    디스플레이   250000      5      1250000
3     USB     저장장치    12000     50       600000
4     노트북      컴퓨터  1200000      3      3600000

In [195]:
#6번
df_products['total_value'].sum()

np.int64(6200000)

In [196]:
#7번
df_products[df_products['category']=='주변기기']

  product category  price  stock  total_value
0     키보드     주변기기  30000     10       300000
1     마우스     주변기기  15000     30       450000

In [197]:
df_products.to_excel('../data/상품정보.xlsx')